exports_files(["labelmap_yolo.txt"])

exports_files(["labelmap_surfnet.txt"])

exports_files(["yolov5s-fp16.tflite"])

exports_files(["yolov5s-fp16-optimize.tflite"])

exports_files(["yolo_surfnet-fp16.tflite"])

exports_files(["yolo_surfnet_fix.tflite"])

exports_files(["yolo_pau-fp16.tflite"])