load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "surfnettrack",
    calculators = [
        "//mediapipe/surfnet/graphs/tracking:mobile_calculators",
    ]
)